---
# this file is used to specify github actions
name: Checks

on: [push] # trigger when code is pushed

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # run these github actions on ubuntu OS, ubuntu has docker compose pre-installed
    steps: 
      - name: Login To Docker Hub # logging to docker hub to pull images
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # checking out the code from repo
        uses: actions/checkout@v2
      - name: Test # running unit test cases
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint # running lint
        run: docker compose run --rm app sh -c "flake8"